name: Validator

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: psf/black@stable
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test challenge 1
      continue-on-error: true
      run: |
        python challenge1_brute_forcing/test/verify_submissions.py
    - name: Test challenge 2
      continue-on-error: true
      run: |
        python -m challenge2_ISS_apis.test.verify_submissions
    - name: Test challenge 3
      continue-on-error: true
      run: |
        python challenge3_RPi_sensors/test/verify_submissions.py
    - name: Test challenge 4
      continue-on-error: true
      run: |
        python challenge4_twilio/test/verify_submissions.py
    - name: Test challenge 5
      continue-on-error: true
      run: |
        python -m challenge5_performances.test.verify_submissions.py