name: Validator

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test challenge 1
      if: always()
      run: |
        python challenge1_brute_forcing/test/verify_submissions.py
    - name: Test challenge 2
      if: always()
      run: |
        python challenge2_ISS_apis/test/verify_submissions.py
    - name: Test challenge 3
      if: always()
      run: |
        python challenge3_RPi_sensors/test/verify_submissions.py
    - name: Test challenge 4
      if: always()
      run: |
        python challenge4_twilio/test/verify_submissions.py
    - name: Test challenge 5
      if: always()
      run: |
        python challenge5_performances/test/verify_submissions.py